name: Java CI with Gradle

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2 # v3.1.0
      with:
        gradle-version: '8.8'

    - name: Init gradle wrapper
      run: gradle wrapper

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle wrapper
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4 #https://github.com/actions/upload-artifact/releases
      with:
        name: BetterBounty
        path: build/libs/BetterBounty v**.jar
